### ISSUE TITLE
4.6 packages no longer available

### ISSUE THREAD

**Issue by mcandre** [b00ga/packer-templates#1]
Thank you for publishing Vagrant boxes and packer templates for DragonFly BSD, this is super helpful for anyone trying to quickly boot DragonFly and experiment!

Say, any idea why `sudo pkg update` is failing?

```console
$ sudo pkg update
Updating Avalon repository catalogue...
pkg: 
http://mirror-master.dragonflybsd.org/dports/dragonfly:4.6:x86:64/LATEST/meta.txz: Not Found
repository Avalon has no meta file, using default settings
pkg: 
http://mirror-master.dragonflybsd.org/dports/dragonfly:4.6:x86:64/LATEST/packagesite.txz: Not Found
Unable to update repository Avalon
```

I hear that DragonFly BSD limits package updates to the latest two release versions, and DragonFly 5.0 just released! Does this mean that the packer template will have to update to at least DragonFly 4.8 in order to get `pkg` working again?

http://lists.dragonflybsd.org/pipermail/users/2015-September/312317.html

**Comment by b00ga** [comment]
Looking at the DragonFly mirror sites, it looks like they maintain packages for current (5.0), previous (4.8) and to-be-next (5.2) releases.

I tried seeing how easy or not it is to add packages to a 4.6 system. You can do dports from source, but it really seemed like more trouble than it was worth.

I always meant to spin a 4.8 box after its release, but just never got around to it (and thought of it again when I saw the 5.0.0 announcement).

Anyway, thanks for the poke. It encouraged me to take a look.
https://app.vagrantup.com/b00ga/boxes/dragonfly48
https://app.vagrantup.com/b00ga/boxes/dragonfly50

Enjoy!

-Shawn
