### ISSUE TITLE
404 Not Found for dragonfly50 and dragonfly48 boxes

### ISSUE THREAD

**Issue by mcandre** [b00ga/packer-templates#2]
Per the Vagrant Cloud page describing the v5.0 box:

https://app.vagrantup.com/b00ga/boxes/dragonfly50/versions/0.1.0

When I try to use the Vagrantfile:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "b00ga/dragonfly50"
  config.vm.box_version = "0.1.0"
end
```

And `vagrant up`, I get:

```console
$ vagrant up 
==> default: VM not created. Moving on...
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'b00ga/dragonfly50' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 0.1.0
==> default: Loading metadata for box 'b00ga/dragonfly50'
    default: URL: https://vagrantcloud.com/b00ga/dragonfly50
==> default: Adding box 'b00ga/dragonfly50' (v0.1.0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/b00ga/boxes/dragonfly50/versions/0.1.0/providers/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found
```

Looks like something is wrong with the Vagrant Cloud setup for this box?

I get the same 404 error for the dragonfly48 box as well. :/

**Comment by b00ga** [comment]
Hrmmm, looks like something borked with my uploads.

I reuploaded them both tonight. Verified them both by redownloading them with a "vagrant init --minimal b00ga/dragonfly48" (and then 50) and made sure I could download, up, ssh, pkg update, pkg install git and make a git clone.

Everything worked fine so I think it's all set now.

-Shawn

**Comment by mcandre** [comment]
I can now successfully get the boxes, thanks for re-uploading!
