### ISSUE TITLE
boxes not integrating with the file provisioner

### ISSUE THREAD

**Issue by mcandre** [b00ga/packer-templates#4]
Whenever the user connects to the dragonfly box via `vagrant ssh [-c]`, the fortune program is executed, creating extra output.

```console
$ cat /usr/share/skel/dot.login
# $FreeBSD: src/share/skel/dot.login,v 1.14.2.2 2001/08/01 17:24:32 obrien Exp $
# $DragonFly: src/share/skel/dot.login,v 1.3 2006/03/17 03:16:51 justin Exp $
#
# .login - csh login script, read by login shell, after `.cshrc' at login.
#
# see also csh(1), environ(7).
#

[ -x /usr/games/fortune ] && /usr/games/fortune dragonfly-tips

$ cat /usr/share/skel/dot.profile 
# $FreeBSD: src/share/skel/dot.profile,v 1.19.2.2 2002/07/13 16:29:10 mp Exp $
#
# .profile - Bourne Shell startup script for login shells
#
# see also sh(1), environ(7).
#

# remove /usr/games if you want
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/usr/pkg/sbin:/usr/pkg/bin:$HOME/bin; export PATH

# Setting TERM is normally done through /etc/ttys.  Do only override
# if you're sure that you'll never log in via telnet or xterm or a
# serial line.
# Use cons25l1 for iso-* fonts
# TERM=cons25; 	export TERM

BLOCKSIZE=K;	export BLOCKSIZE
EDITOR=vi;   	export EDITOR
PAGER=less;  	export PAGER

# set ENV to a file invoked each time sh is started for interactive use.
ENV=$HOME/.shrc; export ENV

[ -x /usr/games/fortune ] && /usr/games/fortune dragonfly-tips
```

I made local copies of these configuration scripts, removing the fortune invocations, and attempting to use the `file` provisioner to replace the scripts in the box:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "b00ga/dragonfly50"
  config.vm.box_version = "0.1.1"

  config.vm.provision "file", source: "dot.login", destination: "/usr/share/skel/dot.login"
  config.vm.provision "file", source: "dot.profile", destination: "/usr/share/skel/dot.profile"
end
```

However, it looks like the `file` provisioner does not currently work with the dragonfly boxes:

```console
$ vagrant up
==> default: Running provisioner: file...
Failed to upload a file to the guest VM via SCP due to a permissions
error. This is normally because the SSH user doesn't have permission
to write to the destination location. Alternately, the user running
Vagrant on the host machine may not have permission to read the file.

Source: /Users/andrew/go/src/github.com/mcandre/vagrant-dragonfly-rust/dot.login
Dest: /usr/share/skel/dot.login
```

Could the file provisioner be fixed for the dragonfly boxes?

**Comment by b00ga** [comment]
The fortune invocations are not called from _/usr/share/skel_. That directory contains a set of files to place in a new user's home directory (a home directory "skeleton", hence the name).

When the DragonFly BSD box is spun and the vagrant user is created, the skeleton files are copied to the vagrant user's home directory. There are files there for initialization of different shells. For the "typical Linux experience", that I presume many Vagrant users expect, I chose to make "bash" the user shell (not the DragonFly default). In the case of bash, the file that is causing the fortune execution is ".profile" (_/home/vagrant/.profile_ technically speaking).

When operating system support is written into vagrant, there are a series of capabilities defined. The person(s) implementing support for that OS add ruby code to effect that feature for the given OS. From the output you've provided, it appears that there is no support for the "file" provisioner for either DragonFly specifically or BSD generally in Vagrant.

If the fortunes really bother you, you can use a shell provisioner in your Vagrantfile to remove the offending line from _.profile_. I tested the following and it appears to work fine:
`  config.vm.provision "shell",
    inline: "sed -i -e '/fortune/d' .profile"`

This _sed_ command says, use an extended regular expression (-e) to edit the file _.profile_ in-place (-i). The regex says "match lines that contain the string _fortune_ and delete (d) them."

-Shawn
